### ISSUE TITLE
Document Faraday integration

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#106]
Requires ActiveSupport Notifications subscriber: https://github.com/lostisland/faraday_middleware/wiki/Instrumentation

**Comment by tombruijn** [comment]
We could also offer this as an automatic integration?

**Comment by matsimitsu** [comment]
Do we still want to do this? I think we can close this.

**Comment by tombruijn** [comment]
If it supports ActiveSupport::Notification by adding `conn.use :instrumentation` to it, we can add a page that detail just that?

**Comment by noccor** [comment]
Closing this issue because it is stale.
