### ISSUE TITLE
Limiting requests guide

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#114]
Because we want to help people keep within their plan (within reason)

- Ignore actions/exceptions/namespaces
- Ruby: Discard transactions from (search) bots

**Comment by matsimitsu** [comment]
Hmm looks like this was done already? ( http://localhost:4567/ruby/configuration/ignore-actions.html ) Or do we want a page that covers all languages we can point users to?

**Comment by tombruijn** [comment]
This issue was meant as a step by step guide for things to do to reduce the number of requests. Ignore actions (which ones), namespaces (which ones). The things we do in support requests when we help people fit in a plan. Maybe there's some good copy in Intercom we can use for this?
