### ISSUE TITLE
Ruby: Implementing custom formatters

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-docs#120]
As reported in https://github.com/appsignal/appsignal-ruby/issues/321, we need more thorough documentation for implementing custom formatters.

**Comment by tombruijn** [comment]
See also changes made in https://github.com/appsignal/appsignal-ruby/pull/397
about how to set this up

**Comment by matsimitsu** [comment]
Fixed in: https://docs.appsignal.com/ruby/instrumentation/event-formatters.html . Can you close it @tombruijn ?

**Comment by tombruijn** [comment]
Yeah looks like I wrote the page for a month later? Weird I didn't close it. Closing!
