### ISSUE TITLE
JS error: local storage is disabled in Safari's private browsing mode

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-docs#122]
As [reported via twitter](https://twitter.com/clemensk/status/887640096769552384):

![](https://pbs.twimg.com/media/DFGH9P3XcAELh11.png)

https://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

**Comment by tombruijn** [comment]
so... cookies?

**Comment by tombruijn** [comment]
As reported on the StackOverflow issue:

> UPDATE: This has been fixed in Safari 11, so the behaviour is now aligned with other browsers.

I don't have the problem locally anymore. Closing!
