### ISSUE TITLE
Link to rubydoc.info and hexdocs.pm for code documentation

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#138]
A lot of our pages include code examples of how to do something with an AppSignal integration. To allow users to explore using these examples further we should link to the related helper methods on rubydoc.info or hexdocs.pm.

- http://www.rubydoc.info/gems/appsignal
- https://hexdocs.pm/appsignal/Appsignal.html

**Comment by noccor** [comment]
Closing because this issue is stale.
