### ISSUE TITLE
Update required packages for Operating Systems to list specific packages

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#161]
- List specific packages per OS
  - For alpine linux, see linked Intercom thread: `apk add --update make gcc musl-dev musl-utils`
- Make a note that these packages are only necessary for the gem installation/Elixir compilation and not a runtime so users can optimize their image sizes

https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/15523781185

**Comment by tombruijn** [comment]
FreeBSD does not seem to need the `gcc` package: https://github.com/appsignal/appsignal-elixir/pull/483#issuecomment-487976632

**Comment by noccor** [comment]
Closing because this issue is stale.
