### ISSUE TITLE
Document `Problem with the SSL CA cert`

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-docs#164]
Form support https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/15947543341 (private Intercom link)

- ca-certicates package
- time on the server out of sync?

**Comment by thijsc** [comment]
Why not fix it like in Ruby?

**Comment by tombruijn** [comment]
This particular issue is about the Ruby gem, but it would be nice to have a "known issue" package for this type of error so we can point to it whenever someone encounters it.
Not sure yet why it's happening in this instance though.
