### ISSUE TITLE
Update gem version

### ISSUE THREAD

**Issue by roytomeij** [appsignal/appsignal-docs#17]
Right now we say the latest gem version is 1.0 at http://docs.appsignal.com/getting-started/supported-frameworks.html. We should probably change that to `1.x` so this doesn't need regular updates.

Also, people seem confused by the line about `0.11` for Windows and jRuby. My best guess is that people will copy and paste the first code block they encounter, which makes sense. We should probably have the first code block be about the `1.x` branch.

**Comment by thijsc** [comment]
Fixed in dbcb8a2eaeb3fb4f913e4f935fd15234ebcf37d2
