### ISSUE TITLE
APPSIGNAL_APP_ENV needs an entry in appsignal.yml

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#176]
Just defining the env name in the system env won't work if it's not in the yml file when using both a config yml file and system env vars. It's assuming the entire config is defined in the env.
Document this better in the `APPSIGNAL_APP_ENV` option.

```
export APPSIGNAL_APP_ENV=custom_env
```

```yml
custom_env:
  <<: *defaults
  active: true
```

From support: https://app.intercom.io/a/apps/yzor8gyw/inbox/all/conversations/16281405510

**Comment by thijsc** [comment]
This will work if you don't have a config file at all by the way.

**Comment by tombruijn** [comment]
Comment from https://github.com/appsignal/appsignal-ruby/issues/337:

> Quick comment, this would be fixed if using ERB to also create the env group:
> 
> ```yml
> <%= ENV['RELEASE_STAGE'] %>:
>   active: true
> ```

**Comment by tombruijn** [comment]
Documented the env var key in the yaml file in this commit: https://github.com/appsignal/appsignal-docs/commit/8d13e8d4e4a356be71e547f94972de1f9912371e

Closing for now. We don't want to build a new system for support a new `env` config key in the config file for now. We may revisit it later when we ensure all the integrations are consistent. (For as much as that is possible because not all languages will support the same config methods.)
