### ISSUE TITLE
Update Slack notification docs

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-docs#193]
From [support](https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/19529562329) (private intercom link):

> how do I setup a slack integration? I can only see github app integration on the integrations tab

We should update the screenshots and documentation for setting up a Slack notification

**Comment by tombruijn** [comment]
Related: https://github.com/appsignal/appsignal-server/issues/3071

**Comment by tombruijn** [comment]
Maybe we can ping Slack to update the instructions and screenshots at least without us creating a new slack app.

**Comment by tombruijn** [comment]
How the page currently looks when adding an AppSignal integration in Slack:

![appsignal slack app directory 2018-11-19 15-00-11](https://user-images.githubusercontent.com/282402/48711543-d8bf2100-ec0b-11e8-8b95-df46d7e5b347.png)

**Comment by tombruijn** [comment]
> Hi Tom,
> 
> Thanks very much for reaching out about the installation instructions for the AppSignal app that we maintain. Appreciate the updated instructions. I will pass these onto our App Directory team so that they can publish the updates.
> 
> We'll reach out if there are any questions or issues that arise while completing this.
> 
> Thanks again!
> Adam

**Comment by tombruijn** [comment]
Still not updated on Slack's end.

**Comment by tombruijn** [comment]
Still not updated on Slack's end.

**Comment by tombruijn** [comment]
Pinged Slack again.

**Comment by tombruijn** [comment]
Slack updated the docs 🎉
Closing
