### ISSUE TITLE
Document graphQL endpoint

### ISSUE THREAD

**Issue by jvanbaarsen** [appsignal/appsignal-docs#222]
We are pointing more and more users towards our GraphQL endpoint. Might be a good idea to document how to use it, and what the restrictions are.

**Comment by tombruijn** [comment]
We need to finish this PR with the latest changes: https://github.com/appsignal/appsignal-docs/pull/84
But that requires us to stabilize the GraphQL API first: https://github.com/appsignal/appsignal-server/issues/2272

Let's continue it in https://github.com/appsignal/appsignal-server/issues/2272
