### ISSUE TITLE
Appsignal for Javascript v1.0 docs

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-docs#231]
Tracking docs changes that need to take place before we ship 🚢 

- [x] Plugins
  - [x] Architecture
  - [x] How to write one
- [x] Integrations
  - [x] Architecture
  - [x] How to write one
- [x] Hooks
  - [x] Decorators
  - [x] Overrides
- [x] Vue integration
- [x] Angular integration
- [x] Ember integration
- [x] Preact integration
- [x] Update `appsignal-javascript` repo README

**Comment by tombruijn** [comment]
@xadamy can we close this? Is everything on the checklist done?

**Comment by xadamy** [comment]
Indeed, this is now done @tombruijn 👍
