### ISSUE TITLE
Add documentation for breadcrumbs

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-docs#249]
We currently have no documentation for the breadcrumbs feature, so this will need to be added before launch.

@matsimitsu Just checking to ensure I'm understanding how the fields should be used:

`action` = UI | Network | Navigation | Console
`message` = “The user clicked a button” | “HTTP 500 from http://blablabla.com” | “The user pressed back” | “A console.log message”

`metadata` = key/value metadata in <string, string> format

Does this seem okay to you?

**Comment by matsimitsu** [comment]
Yes!
