### ISSUE TITLE
Building in parallel is broken

### ISSUE THREAD

**Issue by jvanbaarsen** [appsignal/appsignal-docs#269]
Because of an unknown issue running the `middleman build` script is failing on `source/ruby/configuration/options.html.erb`. The failure isn't there when you run `middleman build --no-parallel`.

For now we need to use that workaround, but this is something that we probably should fix.

I'll make sure to add a wrapper around the build script so building remains simple.

**Comment by tombruijn** [comment]
I think I fixed it in #397. Let me know if it occurs again.
