### ISSUE TITLE
Wrong word on custom metrics page

### ISSUE THREAD

**Issue by jonasbrinkhoff** [appsignal/appsignal-docs#306]
> Counters are good to use to track events. With a gauge you can track how many of something (users, comments, etc.) there is at a certain time, but with **events** you can track how many events occurred at a specific time (users signing in, comments being made, etc.).

I think **events** is supposed to be counters?

**Comment by tombruijn** [comment]
@jonasbrinkhoff on what page is this? If you want you can also send in a PR with the change already. I think what you're suggesting is correct.

**Comment by jonasbrinkhoff** [comment]
It's on this page: https://docs.appsignal.com/metrics/custom.html

Don't have the headspace at the moment to get into the code of the docs (first time making a PR for this), but I can do it later.
