### ISSUE TITLE
Documentation Redesign

### ISSUE THREAD

**Issue by jonasbrinkhoff** [appsignal/appsignal-docs#330]
We want to refresh the look of the documentation.

Design: https://www.figma.com/file/JTJerpdO1zzihdVBympX6c/Documentation?node-id=124%3A0

### Must-dos
- [ ] Header
  - [x] Update to new design
  - [ ] Add active state for "Docs"
- [ ] Layout
  - [x] Implement new layout
  - [x] Make layout responsive
- [ ] Navigation
  - [x] Update to design system
  - [x] Active states
  - [ ] Responsive behaviour?
- [x] Search bar
  - [x] Update to match new design
- [ ] Content
  - [x] Add tailwind typography
  - [ ] Adjust design of text components
  - [ ] Update design of `hr`
- [x] Footer
  - [x] Convert to design system
- [x] "On this page" section
  - [x] Create mockup of section
- [ ] General
  - [x] Upgrade FontAwesome
  - [ ] Remove unused CSS
  - [x] Check if it's possible to remove the whole design language?
- [ ] For Jeroen
  - [ ] Check On this Page section
  - [ ] Check active system

### Nice-to-haves
- [ ] Content
  - [ ] Add title to code block
  - [ ] Add link box
  - [ ] Figure out what to do with tables
- [ ] "On this page" section
  - [ ] Write script to automatically create table of contents
- [ ] Footer
  - [ ] Update design

**Comment by tombruijn** [comment]
@jonasbrinkhoff can this be closed now that #344, #341 are merged?

**Comment by jonasbrinkhoff** [comment]
> @jonasbrinkhoff can this be closed now that #344, #341 are merged?

Yes :)
