### ISSUE TITLE
Deploy markers with Cloud66

### ISSUE THREAD

**Issue by jean-tymate** [appsignal/appsignal-docs#348]
Extract from your documentation :

### Cloud66 Support

If you'd like to use the Deploy Marker feature with [Cloud66](https://www.cloud66.com/), you can do this by adding/updating the following line in your config file:

```yml
# For Ruby
# config/appsignal.yml
revision: "<%= ENV['CLOUD66_SERVICE_GIT_REF'] %>"
```
https://docs.appsignal.com/application/markers/deploy-markers.html#cloud66-support
It does not work, there is no CLOUD66_SERVICE_GIT_REF environnement variable in Cloud66 apps.

**Comment by matsimitsu** [comment]
Hi @jean-tymate Are you using docker containers on cloud66? or the non-docker deploys?

**Comment by jean-tymate** [comment]
I use Rails applications. I did not see any env variables with the current git commit ref.

<img width="285" alt="Screenshot 2020-08-28 at 14 38 19" src="https://user-images.githubusercontent.com/41159238/91561619-384b7400-e93c-11ea-988f-3ddb7d965696.png">

**Comment by matsimitsu** [comment]
Hi @jean-tymate Thanks! We actually got this suggestion from other Cloud66 customers. I've contacted Cloud66 to figure out what the best way to track deploys will be. I'll keep you updated here!

**Comment by jean-tymate** [comment]
@matsimitsu Did you get any answers from Cloud66 ?

**Comment by Kadaaran** [comment]
Hey @jean-tymate 👋 
I'm the one who suggested it, did you connected your GH repo with Cloud66 ?

**Comment by jean-tymate** [comment]
@Kadaaran Yes I used this https://github.com/cloud66-oss/github-actions

**Comment by Kadaaran** [comment]
@jean-tymate I think, not sure about that tbh, that a better way to make sure C66 has access to your code is either
1. to configure it with a SSH Key as explained here: https://help.cloud66.com/rails/how-to-guides/common-tools/access-your-code.html
2. try to setup your GH repo with the toolbelt directly

Then to check if the variable is well set, try to run `env | grep 'CLOUD_66_GIT_REF'`

Let me know if it helps 🙏

**Comment by jean-tymate** [comment]
@Kadaaran It doesn't work :/ Still no `CLOUD_66_GIT_REF` env variables

**Comment by thijsc** [comment]
@matsimitsu did you ever hear back from Cloud66 about this?

**Comment by noccor** [comment]
Closing this issue as it's stale. Please let us know if there is something here that still needs to be worked on!
