### ISSUE TITLE
Docs 'new-application' only mentions Ruby, Elixir and Javascript, not Node.js yet

### ISSUE THREAD

**Issue by aksie** [appsignal/appsignal-docs#374]
"Some language integrations and support for libraries require some manual steps to get set up. Please see our installation instructions for the language of your app for more information.

Ruby installation instructions
Elixir installation instructions
JavaScript installation instructions"

**Comment by tombruijn** [comment]
If it's this page (which I moved), it now lists JavaScript and Node.js: https://docs.appsignal.com/guides/new-application.html
