### ISSUE TITLE
Large JavaScript bundle size

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#383]
Locally the page load is a bit slow, I've noticed. Upon closer inspection I saw it's (partially) a problem with our JavaScript. So let's focus on that in this issue, not the overall slowness.

The JavaScript bundle size is:

- in production (https://docs.appsignal.com/):
  - Transferred: 2.13 MB
  - Actual: 9.35 MB ❗️
- in development:
  - Transferred: 23.04 MB
  - Actual: 23.04 MB ❗️

It's takes a while to load this as shown in the network panel of the Firefox developer console:

![image](https://user-images.githubusercontent.com/282402/96896616-0105c900-148e-11eb-8e90-7453e0d3cb3a.png)

For reference, the AppSignal.com React app (which uses a lot more JavaScript) size in production (AppSignal.com) is:

- Transferred: 475.53 KB
- Actual: 2.10 MB

Questions I have about this that originate from this point as I looked a bit further into it:

- Why is the CSS loaded from JavaScript?
  - If I turn off JavaScript (to speed up the local development environment) the CSS fails. Looks like the CSS is set from JavaScript, which could be the cause of the large bundle size?
- Why is the JavaScript bundle so big?
  - Are things included (like build tools, CSS, images, fonts, other assets) that inflate the bundle size a lot, or shouldn't be shipped to the distribution bundle?

@jvanbaarsen @jonasbrinkhoff can you shed more light on this?

**Comment by jonasbrinkhoff** [comment]
Don't really know much about how javascript bundling works (in general as well as for the homepage project). @jvanbaarsen is probably the person to speak to :)

**Comment by jvanbaarsen** [comment]
@tombruijn I can look into this in the cooldown. We can probably make everything a ton smaller.

**Comment by kouliavtsev** [comment]
This bug is related Middleman (not Nextjs). So closing this one.
