### ISSUE TITLE
Any plan on support more languages.

### ISSUE THREAD

**Issue by shakks** [appsignal/appsignal-docs#451]
Hey, is there any plan on adding support for flask any time soon?

**Comment by shairyar** [comment]
Let me know what language would you like us to support and I will add you to the list of customers who requested it and once it is available we will let you know.

**Comment by shakks** [comment]
Python & its frameworks like flask and django.

**Comment by shairyar** [comment]
Thanks, I will add you to the list of customers who requested it. There is no timeframe available on when supporting that will be possible but it is in the pipeline for sure.
