### ISSUE TITLE
Document Node.js default heap statistics minutely probe

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-docs#532]
[The Node.js integration's docs on minutely probes](https://github.com/appsignal/appsignal-docs/blob/main/source/nodejs/metrics/minutely-probes.html.md) claim that:

> No minutely probes are configured by `@appsignal/nodejs` by default.

In fact, the opposite is true. If `enableMinutelyProbes` is set to true (its default value) then a minutely probe will be registered, which reports metrics related to the V8 engine's heap statistics. This probe is currently undocumented, despite the fact that a magic dashboard for its metrics exists.

[(Note that the behaviour of `enableMinutelyProbes` is not entirely correct either)](https://github.com/appsignal/appsignal-nodejs/issues/544)

We should document this probe, much like the other default probes are documented; see [Elixir's Erlang probe](https://github.com/appsignal/appsignal-docs/blob/main/source/elixir/integrations/erlang.html.md#minutely-probe) for an example.

We should also document how to deactivate the probe without disabling the minutely probes entirely, which is what `enableMinutelyProbes` is _supposed_ to do, although it's not what it currently does.

For the Elixir probe, [the documented way to disable the default Erlang minutely probe is to register a probe that does nothing with the same name](https://github.com/appsignal/appsignal-docs/blob/main/source/elixir/instrumentation/minutely-probes.html.md#overriding-default-probes), although an `unregister` method now exists in the Elixir minutely probes implementation, and it should be used in the documentation instead; a similar method should be implemented for the Node.js integration and used in the documentation.

**Comment by tombruijn** [comment]
@unflxw is this issue addressed in PR #534?

Can we split the Elixir part of this issue into a new issue?

**Comment by unflxw** [comment]
Yes, #534 addresses this. I'll create another issue for changing the Elixir docs to use `unregister/1`, I was just mentioning it here as an example.
