### ISSUE TITLE
Revisit the scope documentation of nodejs

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-docs#537]
Is this true? Looking at the implementation (`withSpan` calls `withContext` on the `ScopeManager`), it seems like [it reverts the stack to the previous span after it's done running the given function](https://github.com/appsignal/appsignal-nodejs/blob/ad40d9d8ec0dcedb38973339d75a18373eb7d3ef/packages/nodejs/src/scope.ts#L145-L152), unless there was no root span. So the span created by `tracer.createSpan()` above would not be `tracer.currentSpan()` down here.

_Originally posted by @unflxw in https://github.com/appsignal/appsignal-docs/pull/531#discussion_r787953354_

**Comment by tombruijn** [comment]
This scopes page seems like the way we should document (in a guide) how to use the spans. What is currently documented on the custom instrumentation page is too technically detailed with implementation nonsense that makes it too difficult. Basically we need an `Appsignal.[tracer().]instrument()` function to hide most of that away.

**Comment by tombruijn** [comment]
An `Appsignal.instrument` function already exists in Node.js and will conflict or be confusing, see issue https://github.com/appsignal/appsignal-nodejs/issues/565 for discussion.

We need to take a closer look at the opentelemetry API that Node.js integration was based on, and if it uses scopes the same way and if we implemented the whole API or not. Hopefully there's some more user friendly things that we didn't get around to implementing back then.
