### ISSUE TITLE
[Absinthe] : Proposed changes to doc

### ISSUE THREAD

**Issue by pkrawat1** [appsignal/appsignal-docs#567]
### What ?
- Appsignal instrumentation is not available for Abisinthe graphql API.

### Existing solution
- Existing workaround suggests a plug to add a plug to set the action name manually for the Absinthe requests.

### Issue
- We cannot find out which Query(body read) was fired on graphql since we cannot read the body from conn during the plug call. Since it will raise multiple body read error.

### Proposed update to doc
- We can create a custom body reader that can read the body for graphql api and send the body to plug parsers.
- following changes can work and track different queries on graphql

```elixir
defmodule CustomBodyReader do
  @moduledoc """
    Custom body reader to send graphql plug info appsignal
  """
  @path "/graphql"
  def read_body(%Plug.Conn{request_path: @path, method: "POST"} = conn, opts) do
    {:ok, body, conn} = Plug.Conn.read_body(conn, opts)
    
    plug_name =
      with query <- Jason.decode!(body),
           operation_name <- query["operationName"] do
        "MyWeb.GraphQL#" <> operation_name
      else
        _ -> "MyWeb.GraphQL#NoOperation"
      end

    {:ok, body, Appsignal.Plug.put_name(conn, plug_name)}
  end

  def read_body(conn, opts), do: Plug.Conn.read_body(conn, opts)
end

```

And update the endpoint Parser config

```elixir
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    ...
    body_reader: {CustomBodyReader, :read_body, []}
```

**Comment by jeffkreeftmeijer** [comment]
Hey @pkrawat1! Thanks for letting us know about this. We keep that page not to break links, but we don’t actively maintain that solution anymore. Of course, you’re welcome to still use it, but we won’t be updating the page with new features like this. If we circle back to this, we might write an implementation and ship it with our package.

Thanks again!
