### ISSUE TITLE
Repalce /nodejs/configuration/ignore-actions.html

### ISSUE THREAD

**Issue by aksie** [appsignal/appsignal-docs#589]
Replace
/nodejs/configuration/ignore-actions.html
or
/ruby/configuration/ignore-actions.html
or
/elixir/configuration/ignore-actions.html

With 

/guides/filter-data/ignore-actions.html

On all pages

**Comment by kouliavtsev** [comment]
@aksie If I click on all the links here they all redirect to `ignore-actions` page.

https://docs.appsignal.com/nodejs/configuration/ignore-actions.html
https://docs.appsignal.com/ruby/configuration/ignore-actions.html
https://docs.appsignal.com/elixir/configuration/ignore-actions.html

![Screenshot 2022-05-30 at 17 46 49](https://user-images.githubusercontent.com/1392575/171026317-a266d681-a597-4352-8658-3bdaf1259046.png)

Could it be that this is already fixed? Or adhref sees this the other way?

**Comment by aksie** [comment]
The redirect works, but ahrefs.com / google prefers no redirects, so we should replace the links with the correct link of where they end up now AFTER the redirect.

**Comment by kouliavtsev** [comment]
@aksie When I checked the source, I did not find any links. Instead, I have found redirects.

Below all instances of: 

- /nodejs/configuration/ignore-actions.html
- /ruby/configuration/ignore-actions.html
- /elixir/configuration/ignore-actions.html

![Screenshot 2022-05-31 at 15 04 10](https://user-images.githubusercontent.com/1392575/171180300-1048d8b6-814c-41dd-adf0-ea6f579afd02.png)

![Screenshot 2022-05-31 at 15 04 44](https://user-images.githubusercontent.com/1392575/171180319-7a37a51a-acb9-4a35-9aa1-ccb7b7a5b5f1.png)

![Screenshot 2022-05-31 at 15 04 56](https://user-images.githubusercontent.com/1392575/171180340-6509d34b-35e1-48c0-a177-bac04c40547b.png)

All are found in `netlify.toml` file.

**Comment by aksie** [comment]
It is not in the source literally, but there are these lists: 

```

   
---
title: "Ruby gem configuration options"
---

<p>The following list includes all configuration options with the name of the environment variable and the name of the key in the configuration file.</p>

<p>For more information on how to configure AppSignal with a configuration file or system environment variables, see our <%= link_to "Configuration", "/ruby/configuration" %> topic.</p>

<%= partial "shared/options_list", :locals => { :integration => :ruby } %>
```

@tombruijn can you point us to where those lists live so we change the link to the right URL without a redirect?

**Comment by tombruijn** [comment]
You're looking for this yml file: https://github.com/appsignal/appsignal-docs/blob/a93f97fa89b5ddcffe5f8fd8a0bb4d1d16fcfcb0/data/config_options.yml#L779

**Comment by aksie** [comment]
@tombruijn thx, fixed it in https://github.com/appsignal/appsignal-docs/pull/605 - please review?
