### ISSUE TITLE
options.erb list still has some wrong URLs

### ISSUE THREAD

**Issue by aksie** [appsignal/appsignal-docs#602]
https://github.com/appsignal/appsignal-docs/blob/aksie-fixmoreredirect/source/nodejs/configuration/options.html.erb
and the same one for ruby and elixir, have links to /nodejs/configuration/ignore-actions.html (and similar with ruby and elixir) that should instead link to: 
https://docs.appsignal.com/guides/filter-data/ignore-actions.html

**Comment by kouliavtsev** [comment]
@aksie 

Can't find `/nodejs/configuration/ignore-actions.html` in https://github.com/appsignal/appsignal-docs/blob/aksie-fixmoreredirect/source/nodejs/configuration/options.html.erb

Instead `/nodejs/configuration/` I see this link.

Should it point to `/guides/filter-data/ignore-actions.html`?

**Comment by kouliavtsev** [comment]
Already fixed
