### ISSUE TITLE
/elixir/instrumentation/tagging.html is missing

### ISSUE THREAD

**Issue by kouliavtsev** [appsignal/appsignal-docs#609]
Found an empty page.

https://docs.appsignal.com/elixir/instrumentation/tagging.html

What content should go here? Or should the page be removed?

**Comment by tombruijn** [comment]
It should link to the tagging guide: https://docs.appsignal.com/guides/custom-data/tagging-request.html#elixir

**Comment by kouliavtsev** [comment]
Fixed
