### ISSUE TITLE
Warning as log_level isn't working

### ISSUE THREAD

**Issue by monteirobrena** [appsignal/appsignal-docs#622]
I tried to setting `warning` to a `log_level` but got this weird error which makes me confused:

```
[WARNING] The 'log_level' of 'warning' is unknown. Please, use one of the following options: error/warning/info/debug/trace
```

Not sure if we need to update the documentation or the AppSignal gem. The other log types are working correctly.

**Comment by shairyar** [comment]
Thanks for reporting that @monteirobrena, we will take a look.

**Comment by tombruijn** [comment]
@shairyar @monteirobrena looks like the log level is currently only picked up as "warn", but we should fix it to (also) use "warning" instead.

**Comment by tombruijn** [comment]
For the team, the change we need to make is here: https://github.com/appsignal/appsignal-agent/blob/7dc1f256b47fcd3c7f0cf5b1a735dfde3bbebd41/common/src/config.rs#L333
I suggest adding "warning" to the match statement for "warn" as well.

**Comment by tombruijn** [comment]
Extension updated to accept "warning" in PR https://github.com/appsignal/appsignal-agent/issues/773
Waiting for integration releases.

**Comment by tombruijn** [comment]
@monteirobrena In Ruby gem 3.1.2 and Elixir package 2.2.16 it now accepts "warning" as a value config option value for `log_level`.
