### ISSUE TITLE
List PGP key on security page

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#64]
PGP is a way to send encrypted emails. It's good to give this option to people who hunt security issues. It's also a good filter to get more serious bounty hunters by referring them to this page and PGP.

**Comment by wesoudshoorn** [comment]
@tombruijn can you explain?

**Comment by tombruijn** [comment]
We should be able to receive PGP encrypted emails on security@appsignal.com. Currently we don't (I think, I haven't set it up) so it should be setup first and then we should share our public PGP key so people can send us encrypted email about security issues they found.

**Comment by tombruijn** [comment]
Closing in favor of https://github.com/appsignal/appsignal-server/issues/3823
