### ISSUE TITLE
OpenTelemetry docs are missing

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-docs#646]
Somewhere in the move to the new NextJS docs page, the links to the OpenTelemetry documentation vanished from the sidebar. The pages are still there ([here's the one for IORedis](https://docs.appsignal.com/nodejs/integrations/opentelemetry-ioredis.html), for example) but they're not linked from the navigation (the IORedis one, for example, should appear under "Node.js > Integrations")

**Comment by wesoudshoorn** [comment]
@noccor this was probably missed when transferring content. Can you take a look?
