### ISSUE TITLE
HTML tags in titles are rendered as plain tags

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#685]
On pages with HTML tags in the title, like `<sup>`, the titles are rendered with the HTML tags visible.

![image](https://user-images.githubusercontent.com/282402/184877377-eeede373-d987-4a6d-86bc-10170606a432.png)

See pages:

- https://docs.appsignal.com/front-end/sourcemaps.html
- https://docs.appsignal.com/elixir/integrations/absinthe.html (it's not supposed to be in the navigation)

**Comment by kouliavtsev** [comment]
We did fix it before, yet it seems either not implemented / or reverted.

https://github.com/appsignal/docs-nextjs/pull/153

Investigating further. 🕵️‍♂️
