### ISSUE TITLE
The /elixir/1.x/ pages link to 404

### ISSUE THREAD

**Issue by kouliavtsev** [appsignal/appsignal-docs#709]
<img width="1227" alt="Screenshot 2022-08-24 at 12 20 50" src="https://user-images.githubusercontent.com/1392575/186394700-cd228a9f-6082-4756-a8dc-4ac4ced2cc74.png">

<img width="1438" alt="Screenshot 2022-08-24 at 12 18 29" src="https://user-images.githubusercontent.com/1392575/186394749-211fd6a1-0eaa-443b-8408-ad8304dcf92b.png">

The links above link to no existing pages:
https://docs.appsignal.com/elixir/1.x/phoenix.html
https://docs.appsignal.com/elixir/1.x/plug.html

**Comment by kouliavtsev** [comment]
@noccor @tombruijn 

To fix this, I need to understand the difference between `/elixir/1.x/` and `/elixir/` pages. Should the content be the same here?

1.) If so, I think it makes sense to remove `/elixir/1.x/` and use a URL rewrite with canonical pointing to `/elixir/`.

<img width="259" alt="Screenshot 2022-08-24 at 12 24 51" src="https://user-images.githubusercontent.com/1392575/186395646-093505a9-9151-4f88-9fae-bf8c1f31a914.png">

2.) Otherwise, we should update the URLs manually. What should we put on the missing pages?

**Comment by tombruijn** [comment]
We split it up at the time so that any new docs for version 2 would not overwrite the version 1 docs. There should be some differences between those two docs. We need to keep the v1 docs.

**Comment by kouliavtsev** [comment]
@tombruijn Thx, for the background.

Then should these:

https://docs.appsignal.com/elixir/1.x/phoenix.html
https://docs.appsignal.com/elixir/1.x/plug.html

Changed to:
https://docs.appsignal.com/elixir/integrations/phoenix.html
https://docs.appsignal.com/elixir/integrations/plug.html

Or do we need to copy the integrations pages to `/1.x/`?

**Comment by tombruijn** [comment]
> - https://docs.appsignal.com/elixir/1.x/phoenix.html
> - https://docs.appsignal.com/elixir/1.x/plug.html

These two pages don't exist. They should be these instead with the integrations directory:

- https://docs.appsignal.com/elixir/1.x/integrations/phoenix.html
- https://docs.appsignal.com/elixir/1.x/integrations/plug.html
