### ISSUE TITLE
"Orphan page" error in Site Audit" (11 URLs affected)

### ISSUE THREAD

**Issue by kouliavtsev** [appsignal/appsignal-docs#712]
<img width="1228" alt="Screenshot 2022-08-25 at 14 44 00" src="https://user-images.githubusercontent.com/1392575/186670196-5ec91933-7d07-49a6-a9cd-e7f99cef5743.png">

In short, this means that there are no internal pages that link to these pages.

https://help.ahrefs.com/en/articles/2694175-orphan-page-error-in-site-audit

All of the URLs are `/elixir/1.x/`.

**Comment by kouliavtsev** [comment]
@tombruijn 

- Is there a specific reason that we don't link to `1.x` pages?
- If we want to avoid duplicate content, we probably should update the canonical of the `1.x` pages.

**Comment by tombruijn** [comment]
> Is there a specific reason that we don't link to 1.x pages?

I don't know. I thought we did.

> If we want to avoid duplicate content, we probably should update the canonical of the 1.x pages (example: /elixir/1.x/why-nif.html).

You mean update to the current page content? Some of these pages may no longer match how the v1.x package works.

**Comment by kouliavtsev** [comment]
> I don't know. I thought we did.

<img width="1440" alt="Screenshot 2022-08-26 at 11 24 39" src="https://user-images.githubusercontent.com/1392575/186873087-cc78bb20-693a-42f6-aa1d-5ec3fe20a870.png">

Can you remember how it was linked? Maybe we could add link to the sidenav or the `Upgrading from AppSignal for Elixir 1.x to 2.x`?

> You mean update to the current page content? Some of these pages may no longer match how the v1.x package works.

Hmm... then it probably does make sense to keep some pages duplicated to avoid complexity.

**Comment by tombruijn** [comment]
> Can you remember how it was linked? Maybe we could add link to the sidenav or the Upgrading from AppSignal for Elixir 1.x to 2.x?

Looks like we didn't link it: https://github.com/appsignal/appsignal-docs/pull/412
Looking back I'm not sure how this should have worked, unless you know the exact URL.
With no way to access it, I'm starting to doubt if we need to keep it. Can we see in the analytics if anyone viewed these pages in the last 3 months? If not, let's remove it.

**Comment by kouliavtsev** [comment]
@tombruijn 

We got some traffic, yet not that much.

<img width="1156" alt="Screen Shot 2022-08-29 at 09 25 03" src="https://user-images.githubusercontent.com/1392575/187163956-08ffd006-f7c2-401e-ac71-c4a1419b1ca8.png">

60 * 0.43 (bounce rate) = 25,8 users over a span of 4 months.

Let's remove the pages and redirect all of them to https://docs.appsignal.com/elixir ?

**Comment by aksie** [comment]
The only reason I can think of why people would see it, is if @shairyar links to it for certain customers. 
If support does that, we need to keep them for those customers. 
If that is not the case, let's remove them and redirect all of them to https://docs.appsignal.com/elixir ?

**Comment by aksie** [comment]
also cc @noccor perhaps he knows?

**Comment by kouliavtsev** [comment]
If we decide to keep the pages and do not want to link to them. We could also exclude them in Ahrefs.

https://help.ahrefs.com/en/articles/1399529-how-to-exclude-specific-pages-from-site-audit-reports

**Comment by shairyar** [comment]
If we have customers using our Elixir integration `v1.x` and, at some point, they plan to update to the latest version, they will find this docs page very helpful.

If there is a way to find out how many customers are still using `v1.x`, that will help in making the decision. It has been a while since I shared that link with anyone.

**Comment by kouliavtsev** [comment]
@shairyar @aksie 

The traffic can be found here https://github.com/appsignal/appsignal-docs/issues/712#issuecomment-1229981117. It is not that much.

Maybe we could add a link to the old documentation on this page:
https://docs.appsignal.com/elixir/installation/upgrading-from-1.x-to-2.x.html

Or...

Simply excluding the URLs in Ahrefs https://github.com/appsignal/appsignal-docs/issues/712#issuecomment-1270243426

**Comment by aksie** [comment]
@kouliavtsev what we can do now is: exclude from a hrefs (can you do so?)
@noccor can you add links to those pages from https://docs.appsignal.com/elixir/installation/upgrading-from-1.x-to-2.x.html ? (however you think is appropriate). Not urgent.

**Comment by kouliavtsev** [comment]
I have excluded the exlixir/1.x pages 👍

@noccor 

I have found more "Orphan pages". These are pages that are not being linked to:
- [ ] /heroku/addon-doc.html 
- [ ] /push-api/deploy-marker.html 
- [ ] /heroku/upgrade-logdrain.html 
- [ ] /elixir/integrations/absinthe.html 

We either have to make them part of the menu, or exclude them from Ahrefs.

**Comment by noccor** [comment]
@jeffkreeftmeijer - hey Jeff, do we still need these pages for upgrading elixir or are they old enough now to be removed?

**Comment by jeffkreeftmeijer** [comment]
I’d say they’re old enough to be removed if we keep the upgrading from 1.x to 2.x page.
