### ISSUE TITLE
Investigate Content Wider than screen

### ISSUE THREAD

**Issue by kouliavtsev** [appsignal/appsignal-docs#736]
Pages reported:
- https://docs.appsignal.com/front-end/sourcemaps.html
- https://docs.appsignal.com/front-end/installation.html
- https://docs.appsignal.com/support/operating-systems.html
- https://docs.appsignal.com/heroku/host-metrics.html

**Comment by kouliavtsev** [comment]
How to fix:

https://microwork.dev/fix-content-wider-than-screen-error/

After running a test in Mobile-Friendly Test everything seems fine.

![Screenshot 2022-09-09 at 17 39 03](https://user-images.githubusercontent.com/1392575/189388652-98629d53-2b08-428b-80eb-9e341373ec22.png)

https://search.google.com/test/mobile-friendly/result?id=UD_54_nY7MHPeOb62jKaUQ

**Comment by aksie** [comment]
It says 'pending validation'
(however, the search console still had it flag this error on Sunday): 

<img width="868" alt="Screenshot 2022-09-12 at 13 01 22" src="https://user-images.githubusercontent.com/28782337/189638016-41f990bc-92a7-4404-9592-ee25b0dbbd78.png">


<img width="814" alt="Screenshot 2022-09-12 at 13 02 04" src="https://user-images.githubusercontent.com/28782337/189638119-1603482a-6e8c-42aa-82f1-81045278a0b5.png">

**Comment by aksie** [comment]
Yay solved! validation passed!

<img width="714" alt="Screenshot 2022-09-13 at 10 26 59" src="https://user-images.githubusercontent.com/28782337/189851798-1fd90170-742d-4e59-a2bc-d9a1598ba90d.png">

**Comment by kouliavtsev** [comment]
Okido, closing this issue then.
