### ISSUE TITLE
Disable data line numbers by default

### ISSUE THREAD

**Issue by kouliavtsev** [appsignal/appsignal-docs#764]
We did this for the blog in https://github.com/appsignal/appsignal-nextjs-blog/pull/611

Motivation:

> Wes proposed this change because very often, the code samples do not benefit from having line numbers. Is it okay to make non-line numbers the default? We can also reverse this behaviour by which the line numbers are there unless you specify it not to be.

- By default data line numbers are disabled.
- When showLineNumbers is added it will show the code block line numbers.

Example:

```
```js showLineNumbers
```

Dependency: `design-system`

**Comment by kouliavtsev** [comment]
@noccor @tombruijn 

Do you agree that we should this for the docs as well or do you have any reasons why we should not do this?

**Comment by tombruijn** [comment]
I think line numbers not being present by default is good 👍 
If we can enable it when needed with `showLineNumbers` that's fine by me.

**Comment by noccor** [comment]
It's only useful when referring to specific lines in larger code blocks, so long as we can switch it on a case-by-case basis, go ahead.

I will need to sanity check the docs to make sure nothing is referring to a line now the lines are gone, but that should not block a merger.

**Comment by kouliavtsev** [comment]
@noccor @tombruijn 

Ok, great!

We will disable the line by default via our `design-system`. This means that all 3 sites (home, blog, docs) will have the same behavior. I will try to get a PR ready this week.

**Comment by kouliavtsev** [comment]
Implement through `design-system`, so the issue is closed.
