### ISSUE TITLE
New terminology 

### ISSUE THREAD

**Issue by raytalks** [appsignal/appsignal-docs#77]
I missed some words on the Terminology page:

Throughput = Total no. of requests sent through the controller in the selected timeframe.
Allocation = The number of times you're distributing memory in your application.
Impact = Duration impact. How much impact does this sample's duration have vs other samples.
Response time = Duration of a request. 
CPU = Hardware in computer that carries out the instructions of a program.
Queue time = How much time it takes for a request to be sent from X to Y (?)
Namespace = Name in Controller to define files and objects (?)

**Comment by wesoudshoorn** [comment]
### Impact = the impact of this controller in comparison to other controllers. 

- Let's say a controller A happens 1000 times with an average duration of 0.5 seconds. The combined duration is 500 seconds.
- Let's say controller B happens 500 times with an average duration of 3 seconds. The combined duration is 1500 seconds.
- Total combined duration of all controllers is 2000 seconds.

This means that 

- Controller A has an impact of 25% (500/2000)
- Controller B has an impact of 75% (1500/2000)

### Queue time
How long a job is waiting in the queue before it is actually executed. 

For example, if it takes you 3 minutes to stand in a queue at the Albert Heyn before you're being helped by the cassier, your queue time is 3 minutes. For your full understanding, if it takes them 1 minute to clear your groceries, the job duration is 1 minute.

**Comment by raytalks** [comment]
PR in https://github.com/appsignal/appsignal-docs/pull/110.
