### ISSUE TITLE
Explain Heroku deploy hooks

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-docs#78]
https://devcenter.heroku.com/articles/appsignal#add-a-deploy-hook-in-heroku

**Comment by jeffkreeftmeijer** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/all/conversations/8067101945?nsrc=slack

**Comment by matsimitsu** [comment]
Already added here: https://docs.appsignal.com/application/markers/deploy-markers.html#heroku-support
