### ISSUE TITLE
Consistent bold formatting of hyperlinks 

### ISSUE THREAD

**Issue by noccor** [appsignal/appsignal-docs#782]
When wrapping a hyperlink in bold tags the link text is not bold, eg: 
![Screen Shot 2022-10-13 at 15 21 39](https://user-images.githubusercontent.com/21147234/195608308-2bcbe53f-bc82-484e-b116-23dec9a60968.png)

**Comment by kouliavtsev** [comment]
@noccor 

Opened a PR with a fix in https://github.com/appsignal/design-system/pull/316

Will be fixed, soon!
