### ISSUE TITLE
Ruby specific things outside Ruby section

### ISSUE THREAD

**Issue by raytalks** [appsignal/appsignal-docs#79]
We noticed (Wes and I) that there are a few things that seem to be Ruby specific, but should also work for Elixir.

- [x] Custom metrics, #69 
- [x] enable_host_metrics for elixir?
- [x] This part: 
![image](https://cloud.githubusercontent.com/assets/13314317/22692930/76fc10ec-ed41-11e6-96bf-6a9e5cd00997.png)
- [ ] Front-end error catching
- [x] Debugging appsignal

There is probably a developer who knows this better than us, but we should check it before Milestone 1.0 :)

**Comment by tombruijn** [comment]
Yes, we have an open issue for these things: https://github.com/appsignal/appsignal-docs/issues/69

- I added custom metrics, tagging, etc to that list
- `enable_host_metrics` is available as a config option: http://docs.appsignal.com/elixir/configuration/options.html#code-appsignal_enable_host_metrics-code-code-enable_host_metrics-code
- Front-end error catching is not something I would want to support in its current version for Elixir. We should make a language independent JS-only version for this.
- Debugging AppSignal, see PR #74
