### ISSUE TITLE
Logger navigation for integrations doesn't entirely open

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#861]
When I visit https://docs.appsignal.com/logging/platforms/integrations/ruby.html

In the navigation sidebar, the logger section opens, but not entirely:

![image](https://user-images.githubusercontent.com/282402/201871213-03a3c622-fd86-486c-8006-fba577e77130.png)

It should look like this:

![image](https://user-images.githubusercontent.com/282402/201871252-83d7de13-1ffc-4edd-ba93-459f84000b04.png)

The same is true for the Elixir and Node.js integrations, as seen in the preview of PR https://github.com/appsignal/appsignal-docs/pull/859

**Comment by noccor** [comment]
Assigning this one to Anton to look into further
