### ISSUE TITLE
Elixir: Appsignal.Phoenix.InstrumenterDSL not found

### ISSUE THREAD

**Issue by scottmessinger** [appsignal/appsignal-docs#98]
Error:
```
** (CompileError) lib/spikey/appsignal_custom_instrumenter.ex:2: module Appsignal.Phoenix.InstrumenterDSL is not loaded and could not be found
```

This appears to have been renamed

**Comment by tombruijn** [comment]
Hi @scottmessinger !

Sorry about that. The `Appsignal.Phoenix.InstrumenterDSL` was removed in https://github.com/appsignal/appsignal-elixir/pull/131 and looks like we forgot to update the docs for that. I'm deploying a new version now.

You should now use the "Elixir custom instrumentation" as described at http://docs.appsignal.com/elixir/instrumentation/instrumentation.html

Thanks for reporting this :)
