### ISSUE TITLE
Appsignal.Instrumentation.Helpers.__using__/1 is undefined or private

### ISSUE THREAD

**Issue by scottmessinger** [appsignal/appsignal-docs#99]
```
** (UndefinedFunctionError) function Appsignal.Instrumentation.Helpers.__using__/1 is undefined or private
```

When I add  `use Appsignal.Instrumentation.Helpers` to my Phoenix controller I get the error above. I'm using the example here: http://docs.appsignal.com/elixir/instrumentation/instrumentation.html#helper-instrument-helper

**Comment by tombruijn** [comment]
Looks like I screwed that part up.

Should be `import Appsignal.Instrumentation.Helpers, only: [instrument: 4]` and not `use`

Also the transaction lookup is misspelled. Should be: `transaction = Appsignal.TransactionRegistry.lookup(self())`

Updating now..

Thanks for the report :)
